# Generated by Django 4.2.16 on 2024-10-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountable_uic', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=100, unique=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('custodian_number', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('manufacturer_part_number', models.CharField(max_length=255)),
                ('manufacturer_year', models.IntegerField()),
                ('manufacturer_model_number', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('site_id', models.CharField(max_length=100)),
                ('stock_number', models.CharField(max_length=100)),
                ('sub_custodian_number', models.CharField(max_length=100)),
                ('sub_location', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_of_issue', models.CharField(max_length=100)),
                ('uic', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('cube', models.IntegerField()),
                ('year_service_life', models.IntegerField()),
                ('dlads', models.BooleanField(default=False)),
                ('ok', models.BooleanField(default=True)),
                ('asset_class', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
