# Generated by Django 4.2.16 on 2024-10-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itec', 'asset_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountablePropertyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCustodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('inventory_date', models.DateField()),
                ('primary_or_alternate', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('date_trained', models.DateField()),
                ('date_received_appointment_letter', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('accountable_property_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='itec.accountablepropertyofficer')),
            ],
        ),
        migrations.CreateModel(
            name='UnitInformationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='sub_location',
            new_name='building_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='custodian_number',
        ),
        migrations.AlterField(
            model_name='asset',
            name='sub_custodian_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PropertyCustodianAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('alternate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_accounts', to='itec.propertycustodian')),
                ('primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_accounts', to='itec.propertycustodian')),
            ],
        ),
        migrations.AddField(
            model_name='propertycustodian',
            name='property_custodian_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodians', to='itec.propertycustodianaccount'),
        ),
        migrations.AddField(
            model_name='propertycustodian',
            name='uic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_custodians', to='itec.unitinformationcode'),
        ),
        migrations.AddField(
            model_name='asset',
            name='property_custodian_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='itec.propertycustodianaccount'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accountable_uic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable_assets', to='itec.unitinformationcode'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='uic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='itec.unitinformationcode'),
        ),
    ]
